# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dce23f03dcd9dddae26453b75b15688c880b48c8dfe0df194adc5ff2b21aca559862f1ce0bad8fe69d41f6f2e7e999b3a18bc3d26abb45e40435c7a93d1bec3c
  cypher:
    key: "\x9B\xEB*+\x87\xB1\xAF\xA0\xF7\x84\xC7\x7F\xF0\xC8B\xB2\x05\xD6\xBD\xED\x7FKD\x8C0\x92\xC6v*[2\xAE"
    iv: "\xEF3\xD5\xB5\xBD\xEA`\x8Fc\x91\x12\xBC"

test:
  secret_key_base: 70da18c23df3ad932da397bb9bd2bbe93534a580cfc988901c287e5c289352c9fc37d1a494343e1b2793712b09932f4ba053f32b5dda3448ea63220bdc3fc729
  cypher:
    key: "\x9B\xEB*+\x87\xB1\xAF\xA0\xF7\x84\xC7\x7F\xF0\xC8B\xB2\x05\xD6\xBD\xED\x7FKD\x8C0\x92\xC6v*[2\xAE"
    iv: "\xEF3\xD5\xB5\xBD\xEA`\x8Fc\x91\x12\xBC"


# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  cypher:
    key: "\x9B\xEB*+\x87\xB1\xAF\xA0\xF7\x84\xC7\x7F\xF0\xC8B\xB2\x05\xD6\xBD\xED\x7FKD\x8C0\x92\xC6v*[2\xAE"
    iv: "\xEF3\xD5\xB5\xBD\xEA`\x8Fc\x91\x12\xBC"

  
  
